# Generated by Django 5.0.4 on 2024-04-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='banco_padrao',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='pessoa_documento',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='pessoa_end',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco_padrao',
        ),
        migrations.RemoveField(
            model_name='site',
            name='pessoa_site',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='site_padrao',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cnae',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='iest',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='sit_fiscal',
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
